### ISSUE TITLE
Add icon to workflow

### ISSUE THREAD

**Issue by gandalfsaxe** [leolabs/alfred-gitmoji#1]
May I suggest: http://www.packal.org/sites/default/files/public/styles/icon_large/public/workflow-files/orgleolabsalfredgitmoji/icon/9b7fe8ac-6582-4825-917e-92d0e0291cc1.png?itok=D5eX7HJI :)

**Comment by leolabs** [comment]
This workflow should already have the icon you suggested. Does it not show up in your version of Alfred when you install it on your machine? :)

**Comment by gandalfsaxe** [comment]
Ah yes it does when I download 1.3 directly from this repo. I downloaded it from http://www.packal.org/workflow/gitmoji at first, so that should be updated :)

**Comment by leolabs** [comment]
I've updated the package in Packal 👍
