### ISSUE TITLE
Use a unique icon for each item

### ISSUE THREAD

**Issue by pghk** [leolabs/alfred-gitmoji#2]
Hi there, thanks for the awesome workflow!

I thought a cool UI change would be to use the emoji itself as the icon of each workflow item.

Alfred doesn’t support using emoji for icons, but we can programmatically grab pngs from [Emoji One](https://github.com/emojione/emojione-assets/find/master) to use instead.

I've had this going over in [my fork](https://github.com/leolabs/alfred-gitmoji/compare/master...pghk:feature/icons) for a while; let me know if you'd like a PR!

### Working example
``` py
emoji = ["🎨","⚡️","✨","🏷️"]
esc_seqs = ['\\U000', '\\u']
for i in emoji:
    unicode_char = i.decode('utf-8')
    ascii_char = unicode_char.encode('unicode-escape')
    codes = ascii_char
    for x in esc_seqs:
        codes = codes.replace(x, " ").split()[0]
    filename = codes.split()[0] + ".png"
    print unicode_char + " -> " + ascii_char + " -> " + filename
```
returns:
```
🎨 -> \U0001f3a8 -> 1f3a8.png
⚡️ -> \u26a1\ufe0f -> 26a1.png
✨ -> \u2728 -> 2728.png
🏷️ -> \U0001f3f7\ufe0f -> 1f3f7.png
```

**Comment by leolabs** [comment]
That looks nice, good idea! Please feel free to open a PR, I'll merge it then.
