### ISSUE TITLE
Script location or permission issue on macOS 12.5

### ISSUE THREAD

**Issue by jrolfs** [leolabs/alfred-gitmoji#5]
I just (finally) upgraded to macOS Monterey and whatever new filesystem crap they introduced seems to have broken a few Alfred workflows, including this one. I'm trying to get to the bottom of it myself, but this is what I'm seeing:

<img width="372" alt="posix_spawn" src="https://user-images.githubusercontent.com/288160/181117446-d5d1e9c3-2ab6-4b8e-b392-5ec4345bf238.png">

...permissions are already `a+x` so I'm thinking it can't find the script?

<img width="974" alt="permissions" src="https://user-images.githubusercontent.com/288160/181118218-cd8cd5cc-58b0-4661-909c-8865b9329687.png">

Let me know if you have any ideas here. I already uninstalled and reinstalled the workflow, but I'll try to poke at a bit more when I have time.

Thanks for the workflow!

**Comment by leolabs** [comment]
Hey @jrolfs, thanks for submitting the ticket!

I'm in the same boat as you, so far I haven't been able to find a solution to make the workflow work on Monterey unfortunately. Let me know if you find any solution to this :)

**Comment by jrolfs** [comment]
I made a tiny bit of progress here... I should have picked up on this sooner but the initial issue is simply because the system **python2** @ `/usr/bin/python` no longer exists in macOS 10.15. Now, `/usr/bin/python3` _does_ exist, but I ran into library issues with these Python versions as well.

- Updating shebang to `#!/usr/bin/python3` or `#!/usr/bin/env python` (I believe the latter uses my **[asdf](asdf-vm.com/)** Python installation, which we definitely don't want if we're trying to rely on external libraries)
  <img width="1292" alt="shebang" src="https://user-images.githubusercontent.com/288160/183740766-87cf48a5-ecd2-4768-bc70-4eb88b7831a8.png">
- Inlining `gitmoji.py` and selecting `/usr/bin/python3` from Alfred's runtime menu (in hopes it somehow provides the library you're looking for?)
  <img width="1292" alt="inline" src="https://user-images.githubusercontent.com/288160/183740949-ecf52452-d0bd-43f1-ac9e-b3702b9fbd22.png">

I know very little about how Python libraries work and even less about Alfred runtimes. It looks like you're trying to load an Alfred-provided library? Unfortunately, I threw a bit of a wrench in this and have upgraded to Alfred 5 between when I first opened this issue, so there's a chance something changed there too?

**Comment by leolabs** [comment]
Thank you so much for the detailed report! I've changed the script to Python3 as well on my machine and it seems like the library I'm using for the workflow integration is only compatible with Python2 :/

I'll see if I can make it compatible with Python3, it seems that some dependency names have changed a bit, so hopefully it's just a matter of renaming imports properly.

**Comment by techouse** [comment]
I faced this issue a few months ago when Apple decided to remove Python 2 from macOS. So I decided to [write my own in Dart](https://github.com/techouse/alfred-gitmoji) and compile it to a standalone native binary. The binary is signed and notarized by Apple.

**Comment by leolabs** [comment]
Thanks for letting me know! I think I'll archive this project then and point any new visitors to yours :)
